# Generated by Django 3.2.11 on 2022-01-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1995-05-15'),
            preserve_default=False,
        ),
    ]
